### ISSUE TITLE
Webhooks not working?

### ISSUE THREAD

**Issue by proffalken** [tomwpublic/hubitat_sonosButtons#1]
Hello,

Thanks for such a great project.

I'm struggling to get the Album Art to update.

I'm running the node-http-sonos-api server and it has the config with the webhook configured, however I have to force a refresh of the child device in Hubitat before the artwork will update.

I can curl the webhook URL from the server running the sonos api code, and it returns a `200`, I'm not too sure how else I'd troubleshoot this!

Thanks in advance for any support you can provide.

**Comment by tomwpublic** [comment]
You need to do two things:

Add config entry on the server side in settings.json: { "webhook" : "http://<your hubitat IP>:39501" }

Manually set the device network id (dni) on the Hubitat virtual device to the MAC address of the server, in all caps with no colons.

**Comment by proffalken** [comment]
Thanks @tomwpublic - not sure if you want to continue the discussion here or on the forums thread, but this is my current settings.json:

```json
{
  "spotify": {
    "clientId": "IKNOWWHOIAM",
    "clientSecret": "SHHHHHHHHHHHHHHH"
  },
  "webhook": "http://<MY HUB IP>:39501"
}
```

On the hub, I've made sure that the MAC Address is set correctly along with the other settings, however the only time that the AlbumArtwork URI updates is if I click the "refresh" button in the console:

![HubitatSonosSetup](https://user-images.githubusercontent.com/262545/123308950-3894ab80-d51c-11eb-9b75-49d9e657f9d7.png)

**Comment by tomwpublic** [comment]
Resolved here: https://community.hubitat.com/t/album-artwork-image-as-the-background-to-the-media-player/74759/16

**Comment by proffalken** [comment]
@tomwpublic - thanks for all your help.

Thinking about it, if I get the time would you welcome a PR that takes an IP Address for this field and automatically translates it to the appropriate value?

I realise there are only two cases so far in which this appears to have solved things, however I'm wondering if there's something in the various API's in play that would make this a logical step forward.

**Comment by tomwpublic** [comment]
I modified the code to use the node server's IP address if the user leaves the MAC address blank. Thanks for the idea and for help testing the change, @proffalken.

https://github.com/tomwpublic/hubitat_sonosButtons/commit/0cf05fc35f1e4cba5c89e64339b7f5c07a159b02
